# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DoSomething.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Danielaswindow(object):
    def setupUi(self, Danielaswindow):
        Danielaswindow.setObjectName("Danielaswindow")
        Danielaswindow.resize(565, 492)
        Danielaswindow.setMinimumSize(QtCore.QSize(300, 400))
        Danielaswindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        Danielaswindow.setFont(font)
        Danielaswindow.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        Danielaswindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/squid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Danielaswindow.setWindowIcon(icon)
        Danielaswindow.setWindowOpacity(1.0)
        Danielaswindow.setToolTipDuration(-3)
        Danielaswindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 yellow, stop:1 purple);")
        self.centralwidget = QtWidgets.QWidget(Danielaswindow)
        self.centralwidget.setObjectName("centralwidget")
        self.naskiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.naskiCheckbox.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.naskiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.naskiCheckbox.setFont(font)
        self.naskiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.naskiCheckbox.setAutoFillBackground(False)
        self.naskiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.naskiCheckbox.setObjectName("naskiCheckbox")
        self.sharvaliCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.sharvaliCheckbox.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.sharvaliCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sharvaliCheckbox.setFont(font)
        self.sharvaliCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.sharvaliCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.sharvaliCheckbox.setObjectName("sharvaliCheckbox")
        self.shortebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.shortebiCheckbox.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.shortebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shortebiCheckbox.setFont(font)
        self.shortebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.shortebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.shortebiCheckbox.setObjectName("shortebiCheckbox")
        self.iubkaCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.iubkaCheckbox.setGeometry(QtCore.QRect(20, 130, 121, 16))
        self.iubkaCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.iubkaCheckbox.setFont(font)
        self.iubkaCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.iubkaCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.iubkaCheckbox.setObjectName("iubkaCheckbox")
        self.maisuriCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.maisuriCheckbox.setGeometry(QtCore.QRect(20, 150, 121, 20))
        self.maisuriCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maisuriCheckbox.setFont(font)
        self.maisuriCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.maisuriCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.maisuriCheckbox.setObjectName("maisuriCheckbox")
        self.svitriCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.svitriCheckbox.setGeometry(QtCore.QRect(20, 170, 121, 20))
        self.svitriCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.svitriCheckbox.setFont(font)
        self.svitriCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.svitriCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.svitriCheckbox.setObjectName("svitriCheckbox")
        self.imReadyPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.imReadyPushButton.setGeometry(QtCore.QRect(20, 380, 93, 28))
        self.imReadyPushButton.setObjectName("imReadyPushButton")
        self.naskiFeriLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_3.setGeometry(QtCore.QRect(160, 90, 131, 21))
        self.naskiFeriLabel_3.setObjectName("naskiFeriLabel_3")
        self.naskiFeriLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_4.setGeometry(QtCore.QRect(160, 110, 131, 21))
        self.naskiFeriLabel_4.setObjectName("naskiFeriLabel_4")
        self.naskiFeriLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_5.setGeometry(QtCore.QRect(160, 130, 131, 21))
        self.naskiFeriLabel_5.setObjectName("naskiFeriLabel_5")
        self.naskiFeriLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_6.setGeometry(QtCore.QRect(160, 150, 131, 21))
        self.naskiFeriLabel_6.setObjectName("naskiFeriLabel_6")
        self.naskiFeriLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_7.setGeometry(QtCore.QRect(160, 170, 131, 21))
        self.naskiFeriLabel_7.setObjectName("naskiFeriLabel_7")
        self.hoodieCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.hoodieCheckbox.setGeometry(QtCore.QRect(20, 190, 121, 20))
        self.hoodieCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hoodieCheckbox.setFont(font)
        self.hoodieCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.hoodieCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.hoodieCheckbox.setObjectName("hoodieCheckbox")
        self.bezrukavkaCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.bezrukavkaCheckbox.setGeometry(QtCore.QRect(20, 210, 121, 20))
        self.bezrukavkaCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bezrukavkaCheckbox.setFont(font)
        self.bezrukavkaCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.bezrukavkaCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.bezrukavkaCheckbox.setObjectName("bezrukavkaCheckbox")
        self.sharfiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.sharfiCheckbox.setGeometry(QtCore.QRect(20, 230, 121, 20))
        self.sharfiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sharfiCheckbox.setFont(font)
        self.sharfiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.sharfiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.sharfiCheckbox.setObjectName("sharfiCheckbox")
        self.qudiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.qudiCheckbox.setGeometry(QtCore.QRect(20, 250, 121, 20))
        self.qudiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.qudiCheckbox.setFont(font)
        self.qudiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.qudiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.qudiCheckbox.setObjectName("qudiCheckbox")
        self.xeltatmanebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.xeltatmanebiCheckbox.setGeometry(QtCore.QRect(20, 270, 121, 20))
        self.xeltatmanebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.xeltatmanebiCheckbox.setFont(font)
        self.xeltatmanebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.xeltatmanebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.xeltatmanebiCheckbox.setObjectName("xeltatmanebiCheckbox")
        self.botasebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.botasebiCheckbox.setGeometry(QtCore.QRect(20, 290, 121, 20))
        self.botasebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.botasebiCheckbox.setFont(font)
        self.botasebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.botasebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.botasebiCheckbox.setObjectName("botasebiCheckbox")
        self.qoshebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.qoshebiCheckbox.setGeometry(QtCore.QRect(20, 310, 121, 20))
        self.qoshebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.qoshebiCheckbox.setFont(font)
        self.qoshebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.qoshebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.qoshebiCheckbox.setObjectName("qoshebiCheckbox")
        self.ketebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.ketebiCheckbox.setGeometry(QtCore.QRect(20, 330, 121, 20))
        self.ketebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ketebiCheckbox.setFont(font)
        self.ketebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.ketebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.ketebiCheckbox.setObjectName("ketebiCheckbox")
        self.sandlebiCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.sandlebiCheckbox.setGeometry(QtCore.QRect(20, 350, 121, 20))
        self.sandlebiCheckbox.setBaseSize(QtCore.QSize(2, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sandlebiCheckbox.setFont(font)
        self.sandlebiCheckbox.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.sandlebiCheckbox.setStyleSheet("QcheckBox{\n"
"background: qlineargradient(\n"
"    spread:pad,\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:0,\n"
"    stop:0 rgba(128, 0, 128, 255),   /* Purple */\n"
"    stop:1 rgba(255, 255, 0, 255)    /* Yellow */\n"
");}")
        self.sandlebiCheckbox.setObjectName("sandlebiCheckbox")
        self.naskiFeriLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_8.setGeometry(QtCore.QRect(160, 190, 131, 21))
        self.naskiFeriLabel_8.setObjectName("naskiFeriLabel_8")
        self.naskiFeriLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_9.setGeometry(QtCore.QRect(160, 210, 131, 21))
        self.naskiFeriLabel_9.setObjectName("naskiFeriLabel_9")
        self.naskiFeriLabel_10 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_10.setGeometry(QtCore.QRect(160, 230, 131, 21))
        self.naskiFeriLabel_10.setObjectName("naskiFeriLabel_10")
        self.naskiFeriLabel_11 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_11.setGeometry(QtCore.QRect(160, 250, 131, 21))
        self.naskiFeriLabel_11.setObjectName("naskiFeriLabel_11")
        self.naskiFeriLabel_12 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_12.setGeometry(QtCore.QRect(160, 270, 131, 21))
        self.naskiFeriLabel_12.setObjectName("naskiFeriLabel_12")
        self.naskiFeriLabel_13 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_13.setGeometry(QtCore.QRect(160, 290, 131, 21))
        self.naskiFeriLabel_13.setObjectName("naskiFeriLabel_13")
        self.naskiFeriLabel_14 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_14.setGeometry(QtCore.QRect(160, 310, 131, 21))
        self.naskiFeriLabel_14.setObjectName("naskiFeriLabel_14")
        self.naskiFeriLabel_15 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_15.setGeometry(QtCore.QRect(160, 330, 131, 21))
        self.naskiFeriLabel_15.setObjectName("naskiFeriLabel_15")
        self.naskiFeriLabel_17 = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel_17.setGeometry(QtCore.QRect(160, 350, 131, 21))
        self.naskiFeriLabel_17.setObjectName("naskiFeriLabel_17")
        self.naskiFeriLabel = QtWidgets.QLabel(self.centralwidget)
        self.naskiFeriLabel.setGeometry(QtCore.QRect(160, 70, 131, 21))
        self.naskiFeriLabel.setObjectName("naskiFeriLabel")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(130, 380, 93, 28))
        self.resetButton.setObjectName("resetButton")
        self.depresiaRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.depresiaRadioButton.setGeometry(QtCore.QRect(20, 410, 95, 20))
        self.depresiaRadioButton.setObjectName("depresiaRadioButton")
        self.happiRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.happiRadioButton.setGeometry(QtCore.QRect(130, 410, 111, 20))
        self.happiRadioButton.setObjectName("happiRadioButton")
        Danielaswindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Danielaswindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 26))
        self.menubar.setObjectName("menubar")
        Danielaswindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Danielaswindow)
        self.statusbar.setObjectName("statusbar")
        Danielaswindow.setStatusBar(self.statusbar)

        self.retranslateUi(Danielaswindow)
        QtCore.QMetaObject.connectSlotsByName(Danielaswindow)

    def retranslateUi(self, Danielaswindow):
        _translate = QtCore.QCoreApplication.translate
        Danielaswindow.setWindowTitle(_translate("Danielaswindow", "garderobe amigo"))
        self.naskiCheckbox.setText(_translate("Danielaswindow", "ნასკი"))
        self.sharvaliCheckbox.setText(_translate("Danielaswindow", "შარვალი"))
        self.shortebiCheckbox.setText(_translate("Danielaswindow", "შორტები"))
        self.iubkaCheckbox.setText(_translate("Danielaswindow", "იუბკა"))
        self.maisuriCheckbox.setText(_translate("Danielaswindow", "მაისური"))
        self.svitriCheckbox.setText(_translate("Danielaswindow", "სვიტრი"))
        self.imReadyPushButton.setText(_translate("Danielaswindow", "მზად ვარ"))
        self.naskiFeriLabel_3.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_4.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_5.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_6.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_7.setText(_translate("Danielaswindow", "ფერი"))
        self.hoodieCheckbox.setText(_translate("Danielaswindow", "hoodie"))
        self.bezrukavkaCheckbox.setText(_translate("Danielaswindow", "ბეზრუკავკა"))
        self.sharfiCheckbox.setText(_translate("Danielaswindow", "შარფი"))
        self.qudiCheckbox.setText(_translate("Danielaswindow", "ქუდი"))
        self.xeltatmanebiCheckbox.setText(_translate("Danielaswindow", "ხელთათმანები"))
        self.botasebiCheckbox.setText(_translate("Danielaswindow", "ბოტასები"))
        self.qoshebiCheckbox.setText(_translate("Danielaswindow", "ქოშები"))
        self.ketebiCheckbox.setText(_translate("Danielaswindow", "კეტები"))
        self.sandlebiCheckbox.setText(_translate("Danielaswindow", "სანდლები"))
        self.naskiFeriLabel_8.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_9.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_10.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_11.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_12.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_13.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_14.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_15.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel_17.setText(_translate("Danielaswindow", "ფერი"))
        self.naskiFeriLabel.setText(_translate("Danielaswindow", "ფერი"))
        self.resetButton.setText(_translate("Danielaswindow", "reset"))
        self.depresiaRadioButton.setText(_translate("Danielaswindow", "დეპრესია"))
        self.happiRadioButton.setText(_translate("Danielaswindow", "ანტიდეპრესია"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Danielaswindow = QtWidgets.QMainWindow()
    ui = Ui_Danielaswindow()
    ui.setupUi(Danielaswindow)
    Danielaswindow.show()
    sys.exit(app.exec_())
